services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: courses_databases
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: P4ssw0rd@
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
        mysql:
            condition: service_healthy
    environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/courses_databases?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: P4ssw0rd@
    networks:
       - app_network
volumes:
  mysql_data:
networks:
  app_network:

